index.html, script.js
=> Create Task form

index.html
**Goals :-**
Make sure the new folder structure still works without making any changes on Netlify 
With the old folder structure, Netlify looks for an **index.html** file at the root directory but with a new folder structure we have placed everything in **src** 
**Tasks :-**
=> Migration for Netlify with new folder strucutre 

.github/workflows/CI.yml
Link to the ticket: [Github action should run once (currently running twice) on a PR - Issue#202](https://github.com/Real-Dev-Squad/website-dashboard/issues/202)
- Removed the push condition from `.github/workflows/test.yml` file.
- It now runs the GitHub action only once instead of running it twice on a PR.
=> Fix: github action running twice for a PR

src/task/index.html, src/task/script.js, src/task/style.css
Closes #232 
added a selection for the authorized user to select HIGH, MEDIUM, or LOW priority for the task. The choice was included so the information could be used on the status site's task details page.
=> added priority dropdown

src/task/script.js
fixes #256 
PROBLEM:
Please read about it in the above issue
SOLUTION:
On each user input, we are calling the `fetchMembers` function that will fetch all the users and filter the users based on the input query.
We have separated the filter member logic from the fetchMembers function and extracted it in a different function named `filterUser`.
We are calling fetchMembers only once and storing results in a variable called `membersData`. On each user input, we are calling the `filterMembers` function which will filter out users stored in the `membersData` variable.
=> Prevent fetching data on user input

users/discord/components/UserDetailsSection.js
This PR fixes the issue where the UI shows an "Invalid date" due to an incorrect attribute name. The attribute should be `discordJoinedAt` instead of `joined_discord`. The necessary changes have been made in the `UserDetailsSection` file to address this issue.
- Renamed `joined_discord` attribute to `discordJoinedAt` in the `UserDetailsSection` file.
Please refer to the related issue for more context: #385
=> Changed joined_discord to discordJoinedAt in the UserDetailsSection

groups/style.css
This PR has Discord groups selection UI tweaks #411 
Added:
- Repositioned the add role button towards top-left
- Hover effect while hovering over the group list item and mouse pointer
Before:
After:
=> Feat/group selection UI tweaks

__tests__/home/home.test.js, constants.js, index.html, script.js, style.css
closes https://github.com/Real-Dev-Squad/website-dashboard/issues/425
Description:
Implement a "Repo Sync" button on the website dashboard. This button will trigger the synchronization of the repository with the staging environment by calling the Sync API. This button is should be behind a feature flag
=> FEAT: added repo sync button and handlers

index.html, script.js
**Issue :-** https://github.com/Real-Dev-Squad/website-dashboard/issues/433
**What is change?**
- The superuser should be able to run two more API on synceUserStatus button and those API which are not
- Also change the button positioning
Before :-
After :-
Running two API concurrently who are non-dependent to save time :-
Test Coverage :-
=> fix: add option to sync Idle and Active Users on syncUsersStatus button

__tests__/standup/standup.test.js, standup/script.js, standup/style.css, standup/utils.js
closes https://github.com/Real-Dev-Squad/website-dashboard/issues/428 
Description:
The standup page currently fetches and displays data for the current month only. It uses a table to present the standup data of users, showing their daily progress throughout the current month.
However we show show dates chronologically from current date till 2 months back in a reverse order while skipping Sundays
demo:
https://github.com/Real-Dev-Squad/website-dashboard/assets/22434603/41fc74f4-848b-405f-bb60-7b25606c3917
test coverage
=> Show Previous 3 Months Data For Standup data 

__tests__/groups/group.test.js, groups/constants.js, groups/script.js, groups/style.css, groups/utils.js
This pull request aims to address the issue of discrepancies between the `GET discord-actions/groups` API in STAGING and PROD environments. Currently, the API is functioning correctly on STAGING, but it returns an Internal Server Error on PROD. While the exact root cause is still under investigation, there is a consensus that the issue might be related to stale data in the PROD environment.
Fixes: #450 
To resolve this issue and ensure a controlled testing and debugging process, a feature flag mechanism is being introduced to the GET discord-actions/groups API. This feature flag will allow the gradual release of new changes to the API on different environments while maintaining stability in the existing functionality.
The changes utilize the `dev=true` flag from the URL and subsequently …
=> moving the use of modified GET discord-actions/groups api under feature flag

package.json
Reverts the puppeteer version to 20.2.1 which is compatible with node v14.
=> Fix failing puppeteer tests

.vscode/settings.json, __tests__/groups/group.test.js, groups/script.js, groups/utils.js, mock-data/groups/index.js
**It toggles the visibility and functionality of the add and remove button on the dashboard site group section. If a user is already in a group remove button to be shown and if a user is not in a group add button to be shown on the site**
- #424
[Screencast from 16-09-23 11:23:27 PM IST.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/48379860/e1ab44cf-946d-424b-9b3d-91031d69a2bb)
[Screencast from 15-09-23 12:24:19 AM IST.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/48379860/eab1505a-9b91-4760-9532-3d5d64b7dd50)
Remove functionality of the button to remove yourself from the group to be added after this pr for now only UI part has been added as I have divided my task into different issues
- #482
=> Toggle add and remove button functionality according user group data

__tests__/users/onboarding-31-days-multiple-selections.test.js, users/script.js
Hello,
This is a fix for issue #511, the issue ticket says that it is a backend issue but after carefully reviewing the code with the creator, the problem was found in the front end.
While writing the code we did not consider the case where we select multiple checkboxes. The code only covered the part where the checkbox for "onboarding > 31 days" is checked. Look at the below images for a better understanding.
**Image 1:** Working of the current page when 'onboarding>31' is **NOT** selected.
**Image 2:** Working of the page when 'onboarding>31' **is** selected. It sends a wrong API call.
Only adding the other cases in the code was not enough, as after refreshing the page we ran into one more issue.
I had to write a function to change the query parameters if the onboarding>31 checkbox is …
=> Filtering Fixed For Onboarding > 31 feature

__tests__/home/home.test.js, constants.js, index.html, script.js
**Issue** - https://github.com/Real-Dev-Squad/website-dashboard/issues/539
**Changes** - A button is added to the dashboard site for SUPERUSER to run the API and sync the "group-onboarding-31d+" users.
**Demo** -
https://github.com/Real-Dev-Squad/website-dashboard/assets/30263070/aa46d6a0-600d-4e7e-868a-4ec7353235c0
**Test Coverage :**
=> feat: added sync onboarding 31 days plus users button

__tests__/home/home.test.js, constants.js, index.html, mock-data/users/index.js, script.js, style.css, utils.js
**Developer Name:** @khemchand-twt11 
**PR Number(s):**  https://github.com/Real-Dev-Squad/website-dashboard/pull/535
**Backend changes**
**Frontend Changes**
**Database changes**
**Breaking changes (If your feature is breaking/missing something please mention pending tickets)**
**Deployment notes(Any special instructions for the deployment)**
**Tested in staging**
Media to show changes
https://github.com/Real-Dev-Squad/website-dashboard/assets/55826451/61179611-4991-4d3f-aa96-cd5298db1778
=> Dev to Main Sync

__tests__/home/home.test.js, index.html, mock-data/users/index.js, script.js, style.css, utils.js
**Description:**
In this PR, I've fixed an issue related to the GitHub sign-in process. Previously, even after signing in, the "Sign In" button would still be visible.
To improve the user experience, I've made the following changes:
**User Name and Profile Information:** Now, after successfully signing in with GitHub, users will see their name and profile picture instead of sign in button.
**Dropdown Menu on User Click:** When users click on their name or profile picture, a dropdown menu will appear. This menu provides various options for user interactions and navigation.
**Before**
https://github.com/Real-Dev-Squad/website-dashboard/assets/84411728/34ff26fa-6751-4162-ad22-3b9d5a9140da
**After**
https://github.com/Real-Dev-Squad/website-dashboard/assets/84411728/94e87556-b5a0-4c15-9458-68c …
=> User name and Image with dropdown options after sign in

__tests__/users/App.test.js, style.css, users/discord/App.js, users/discord/components/TabsSection.js, users/discord/components/UserDetailsSection.js, users/discord/index.html, users/discord/style.css
Under the issue mentioned above, I have fixed the broken UI of discord users in mobile view which negatively impacts the overall user experience and added the footer. Along with this, I have done some enhancement with the UI as well. Please take a look to below added video and screenshots to know more about the changes.
https://github.com/Real-Dev-Squad/website-dashboard/assets/85179394/2cd91301-42ea-4a63-abdd-9d487da05c15
=> Fix : fixed the broken UI of discord users in mobile view with some UI enhancements.

extension-requests/script.js
I need to display logs inside the accordion. Now, the accordion can be opened in two ways: either by clicking on the arrow icon or its parent div. When the event listener was attached to the icon, logs weren't displayed when the user clicked on the parent div. This is why I needed to update that element. Now, even if the user clicks on the icon, it will ultimately be listened to by its parent through the concept of event bubbling.
- https://github.com/Real-Dev-Squad/website-dashboard/issues/494
NA
- https://docs.google.com/document/d/1sf-BAs7C6wmfjRVS-82X492hcb_7jAfIM-7pWtizuXE/edit
Run `yarn test` and there you can see test case running.
[simplescreenrecorder-2023-10-26_19.29.19.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/5c6f4017-7737-4f36-933a-f4c9bd17e6b8) …
=> Fixed Issue of No Logs Appearing When Clicking on the Parent Div of an Accordion

standup/script.js, standup/style.css
**Issue** 
https://github.com/Real-Dev-Squad/website-dashboard/issues/591
**Description** : 
Currently the data in the table header is divided into two or three lines, creating a lack of uniformity and potentially impacting the user experience. 
**Proposed Solution**
Ensured a consistent three-line text format for the table header text.
**Before** :
**After** : 
**Note** : As this was primarily a styling correction, there were no alterations made to the Tests.
=> change date styling in standup table header

extension-requests/local-utils.js, extension-requests/script.js
If the user's self API takes time to resolve, the whole UI was crashing because at some part of the code it was trying to retrieve values from a variable that is still undefined. To solve this, I've added optional chaining and moved data preparation related to the self API inside DOM event listeners to provide it with some extra time.
Before
- https://github.com/Real-Dev-Squad/website-dashboard/issues/589
NA
Run `yarn test` and there you can see test case running.
To mimic the same issue, I've added a setTimeout just for testing purposes.
Now in this case the UI should not crash and should also render logs.
[simplescreenrecorder-2023-10-30_21.23.31.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/17cced1c-4ec5-41f8-9693-5c126537f314)
=> Bug : Fixed crashing issue

mock-data/taskRequests/index.js, utils/time/index.js
Issue Ticket Number:-
- [#1606](https://github.com/Real-Dev-Squad/website-dashboard/issues/546)
- In continuation of this PR https://github.com/Real-Dev-Squad/website-dashboard/pull/602
Backend changes
Frontend Changes
Database changes
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
None
Eliminates the need for converting to milliseconds since the input was already in milliseconds.
=> Resolves the Milliseconds Conversion

users/details/script.js
The API isn't triggered if someone clicks on the task accordion dropdown while the initial APIs haven't been resolved.
https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/f5329556-3ac9-429d-92e1-5c198775db01
- Infinite scroll should work in all the cases
- https://github.com/Real-Dev-Squad/website-dashboard/issues/601
NA
Run `yarn test` and there you can see the test case running.
https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/8c26e228-888b-4128-b570-1650ff80c0cd
=> Bug : Fixed logic for task accordion

__tests__/taskRequests/taskRequest.test.js, __tests__/taskRequests/taskRequestDetails.test.js, index.html, mock-data/taskRequests/index.js, style.css, taskRequests/constants.js, taskRequests/details/index.html, taskRequests/details/script.js, taskRequests/details/style.css, taskRequests/index.html, taskRequests/script.js, taskRequests/style.css, taskRequests/util.js, utils.js
Date: `4 December 2023`
Developer Name: @Ajeyakrishna-k  @vinayak-trivedi 
----
```js
var requestOptions = {
method: 'POST',
credentials: 'include',
redirect: 'follow'
};
a = ["add-new-fields","add-count-created-time"].forEach((d) => 
fetch(`https://api.realdevsquad.com/taskRequests/migrations/?action=${d}`, requestOptions)
.then(response => response.text())
.then(result => console.log(result))
.catch(error => console.log('error', error)));
```
- #617 
- #618 
- #626 
- #633
**Documentation Updated?**
-   [ ] Yes
-   [x] No
_If your feature adds a new API, then documentation related to the feature like API-Contracts, and Data-models  must be updated._
**Breaking Changes**
-   [ ] Yes
-   [x] No
_If your feature introduces breaking changes or if something is missing, please mention the …
=> sync dev to main

__tests__/task-requests/task-request.test.js, task-requests/script.js
Date: 15-03-2024
---
closes #715 
- This PR addresses issue #715, where the `deleteBadge` function was not correctly deleting badges when the delete icon was clicked.
- The issue was that the `deleteBadge` function was using `e.target.textContent` to identify the badge to delete. However, when the delete icon (an image element) was clicked, `e.target` was the image element, which doesn't have a `textContent` property.
- So the `deleteBadge` function has been updated to use the `Element.closest()` method to find the closest ancestor with the class 'badge' and get the `textContent` of span inside it.
https://github.com/Real-Dev-Squad/website-dashboard/assets/88454618/e20e6469-04ff-40ae-b6fb-41a1a508ce1d …
=> Fix: selected filters badge deletion when x icon is clicked in task-requests page

extension-requests/script.js, task-requests/details/style.css
…layed after 
Date: 8th April 2024
Developer Name: @mehra-sourav 
---
#738 
This PR addresses the issue of the extension requests page becoming blank after all extension requests were addressed. 
The cause of this bug was that the logic implemented for showing the message on 0 cards executed immediately without waiting for the dispersal animation of the dismissed card to complete. I've moved that logic to the end of the animation phase, specifically to the event handler of the 'finish' event.
<details>
https://github.com/Real-Dev-Squad/website-dashboard/assets/36883648/984cf0c5-b816-49d0-99a9-9b63b6d7237d
</details>
<details>
There's some weird network call occurring in the tests that re-fetches the extension request data and …
=> Fix: Display 'No extension requests to show!' message after addressing all requests

__tests__/applications/applications.test.js, __tests__/home/home.test.js, applications/script.js, applications/style.css, applications/utils.js, index.html, mock-data/applications/index.js
closes #784, #788, #792 
- Automatic Modal Display: When a superuser navigates to /application?id=<applicationId>, the modal will automatically be displayed.
- Button State Management: If the application has already been accepted or rejected, the corresponding action button will be disabled.
- Dynamic URL Updates: The URL will update dynamically based on the filters applied, reflecting the selected filter parameters.
- API Limit Adjustment: The API has been updated to fetch 6 applications at a time, ensuring that all available space in the application cards is utilized effectively.
- Enable applications button on dashboard page
https://github.com/user-attachments/assets/75dde7f1-27bd-437d-987e-b721bb2d3e58
=> Fix application modal and routing

task-requests/style.css
Date: 05 Sep 2024
Developer Name: Vaibhav Singh
---
- Closes #810 
<details>
When Signed in:
After Sign out:
</details>
<details>
</details>
=> fix: Displayed error styles breaking on mobile devices

__tests__/extension-requests/extension-requests.test.js, __tests__/user-details/task-duedate-hover.test.js, extension-requests/script.js, mock-data/extension-requests/index.js
Date: 11 Sep 2024
Developer Name: Suvidh Kaushik
---
- Closes #816 
The default order in the extension-requests page is set to oldest first. However, the expected order is newest first(descending)
<details>
</details>
<details>
</details>
=> fix: change the order of extension-requests in the extension request page

__tests__/home/home.test.js, index.html, style.css
Date:  07 Sep 2024
Developer Name:  Nikhil Kumar
1.  Improved styling of the Dashboard page and added description.
2.  Improved the hover effect and the colour.
Screenshots
Image after changes-
Image before changes-
=> Improve Dashboard Site Homepage

__tests__/applications/applications.test.js, applications/script.js, applications/style.css
Date: 24 sep 2024
Developer Name: Dikshant Wavhule
---
#822 
Shows indexing on application cards 1 being the oldest form and the nth is the newest one.
<details>
</details>
https://github.com/user-attachments/assets/445eaeef-7fbb-4067-b0db-8ec50dd29795
<details>
</details>
=> Shows index on pending application cards

.github/workflows/tests.yml, __tests__/extension-requests/extension-requests.test.js
Date: 15-10-2024
Developer Name: vinit
---
- closes #890 
Currently, the tests are failing over the CI/CD due to the latest update in Ubuntu as our tests are running over Ubuntu
ubuntu has introduced some new security updates
https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md#technical-details
echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
this change in configuration stayed for single session/reboot
https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
<details>
</details>
<details>
</details>
=> fix failing tests over Github action

.github/workflows/tests.yml, __tests__/extension-requests/extension-requests.test.js, extension-requests/script.js, extension-requests/style.css
Date: 12/10/2024
Developer Name: Kavya Rishi 
---
- Closes #875 
Currently in the extension requests card when it is loading we see a slight delay in some of the elements being rendered, during that time when those element are being rendered , there is nothing in the UI to show that its being rendered . There is just a blank. This can be seen in the screenshot that i have shared. The data that has already being loaded by the card is inaccessible to the user because of the loading spinner. Hence the loading spinner should be removed and there should be a shimmer in the place of the data that is still being loaded.
<details>
[Screencast from 16-10-24 12:37:48 PM IST.webm](https://github.com/user-attachments/assets/f9d2d63d-1e62-4848-bcc3-9d2956f8f318) …
=> enhancement: added shimmer effect

__tests__/users/App.test.js, users/discord/App.js, users/discord/components/UsersSection.js, users/discord/utils/util.js
Date: 24 Oct 2024
Developer Name: Anuj Chhikara (anuj-chhikara-1)
---
- Closed #899 
This PR resolves an issue where the side panel failed to update when selecting different user cards. Previously, the side panel always displayed data from the initially selected user, regardless of subsequent selections, leading to outdated information and impacting user navigation.
<details>
</details>
<details>
<summary>Change File Tests</summary>
</details>
<details>
<summary>Complete Tests</summary>
</details>
To address the issue of production API calls during test runs, I have added the following conditional code in the utils module:
```javascript
const API_BASE_URL =
window.location.hostname === 'localhost'
? 'https://staging-api.realdevsquad.com'
: …
```
=> Fix: Side panel data not updating when different user cards are clicked

__tests__/groups/group.test.js, groups/createElements.js, groups/render.js, groups/script.js, groups/style.css, groups/utils.js
Date: 04 Dec 2024
Developer Name: @VaibhavSingh8 
---
- Closes #921 
<details>
https://github.com/user-attachments/assets/bea813c7-92f7-4b6c-990a-b913b70ebdb8
</details>
<details>
</details>
=> Remove dev flag from the "/groups" endpoint and add a loader on delete

task-requests/details/style.css
Date: 11 Dec, 2024
---
- Closes #924 
This pull request resolves the issue where content written in code format under "Expected Behavior" and "Current Behavior" on the Task Request page would overflow its container, resulting in a broken UI.
<details>
</details>
<details>
</details>
=> Fix: Prevent Code Format Overflow in Task Request Page

applications/style.css, global.css
Date: 
Developer Name: Vamsi Karumuri
---
- Closes #912 
This PR resolves  issue related to application cards content ui misalignment on applications page
<details>
https://github.com/user-attachments/assets/ec2cb053-8098-4f5f-89c4-53ab2f369f61
</details>
<details>
</details>
=> fix: UI Misalignment and Broken Layout on User Application

__tests__/applications/applications.test.js, __tests__/groups/group.test.js, __tests__/home/home.test.js, __tests__/task-requests/task-requestDetails.test.js, __tests__/user-details/task-duedate-hover.test.js, __tests__/users/onboarding-31-days-multiple-selections.test.js, __tests__/users/onboarding31days.test.js, admin-panel/index.js, applications/utils.js, groups/utils.js, identity-service-logs/utils.js, mock-data/taskRequests/index.js, profile/utils.js, taskEvents/utils.js, utils.js
Date: 28 Dec 2024
Developer Name: Hariom Vashista
---
Fixes: Real-Dev-Squad/todo-action-items#255 repo#9
This PR aims at updating the deprecated API endpoint from /users/self to /users?profile=true 
<details>
The updated API endpoint is working properly.
</details>
<details>
Test Case results after and before the changes. Create a new repo and ran npm run test (left side) and then made the changes after checking out in a new branch and ran npm run test (right side)
</details>
=> Updated deprecated API endpoint users/self to users?profile=true

task-requests/details/script.js
Date: 10 Jan 2025
---
- Closes #880
This PR fixes the issue with improper mardown on the TCR page. 
Updated the body content processing to replace single newlines (\n) with double newlines (\n\n) for better Markdown interpretation.
<details>
https://github.com/user-attachments/assets/a255ab48-d33a-4cd2-882f-b9a834713e41
</details>
<details>
</details>
=> Fix: Markdown Rendering Issue on the TCR Page

requests/constants.js, requests/script.js
Date: 14 Mar 2025
Developer Name: @Mridxl
---
- Closes #959 
This PR fixes the incorrect error message shown when a non-super user clicks the "Accept" or "Reject" button on requests. Additionally, it ensures that request cards remain visible on the page instead of disappearing when an error occurs. The error message will now be displayed only via a toast notification without altering the state of the request list.
<details>
</details>
<details>
<summary>Screen Recording</summary>
https://github.com/user-attachments/assets/cd806716-be43-4e4e-a9c4-66fb9c67d12f
</details>
<details>
</details>
=> Fix: Incorrect Error Message and UI issues for Non-Super Users on Request Actions  

__tests__/applications/applications.test.js, __tests__/components/filter.test.js, __tests__/extension-requests/extension-requests.test.js, __tests__/requests/requests.test.js, __tests__/task-requests/task-request.test.js, components/filter/style.css, mock-data/requests/index.js
Date: 29 March 2025
---
- #987 
This PR adds test coverage for the reusable Filter component.
- A dedicated test file has been created to validate the core functionality of the Filter component, including UI rendering and button event listeners.
- Since the Filter component is used across four different pages, we've also added tests in each respective page's test file to ensure that the component renders correctly and displays the appropriate content in each context.
Feature PRs
- #988 
- #989
<details>
- Application Page
https://github.com/user-attachments/assets/59bfa0a0-f707-4b47-9fac-67fe7d871a06
- Extension Requests Page
https://github.com/user-attachments/assets/641fa769-f72a-49b4-b3f5-39e0d5ccb591
- Requests Page …
=> Add Tests for Reusable Filter Component

__tests__/extension-requests/extension-requests.test.js, extension-requests/constants.js, extension-requests/script.js
Date: 24/09/2025
Developer Name: @JAHANWEE
---
- closes  #1016 
This PR fixes the arrow visibility issue in the extension card when `dev=false`. Previously, the arrow was white and invisible against the white background. 
Added a black arrow in `constants.js`.
- Replaced the white arrow with the black arrow for the `dev=false` scenario.
- Added a check to ensure the correct image is  being rendered 
<details>
</details>
https://github.com/user-attachments/assets/2692c1ec-4bfd-44fb-a9d6-5c8c1f4b2c07
<details>
</details>
Update the extension requests UI to use the black down-arrow icon on the accordion button, and add a test to verify this rendering.
To ensure visual consistency with a black chevron down icon on the accordion, …
=> Fixes arrow on extension card
