index.html
main.css

Added some styling to the task form. Also made a dropdown menu for the status, users can choose between active and pending statuses.

added styling with css to the taskform

---

script.js

endpoint changed from `staging-api` to `api.realdevsquad.com`

Change base url to prod endpoint

---

index.html

There is a blocked status now on the task form. This can be used to block certain task that are not to be done until otherwise stated.

added blocked as a status for certain users who are blocked

---

index.html
main.css

I have changed the status option of none to blocked. I also added the styling to the taskForm as you can see in the before and after screenshots.

changed the status of none to blocked

---

css/wallets.css
index.html
js/wallets.js
main.css
wallets.html

Page displays wallets of users

---

main.css

Revert PR #11 and pick up changes from PR #15

---

index.html
main.css
script.js

Refactor task form #21

---

script.js

To convert isNoteworthy to Boolean I used:
`isNoteworthy = (isNoteworthy == 'true')`

Changed isNoteworthy to Boolean

---

index.html
main.css
script.js

Loading spinner on form submit button #31 
Closes #31

Add:loading spinner on form submit button

---

css/wallets.css
index.html
main.css
wallets.html

I added the footer to wallet.htm file as well
Closes #30

Added repo link in footer

---

css/wallets.css
index.html
js/wallets.js
main.css
wallets.html

sync develop

---

.vscode/settings.json
index.html
main.css

worked on purpose field into a text area

---

main.css

Submit button earlier : 
Submit button after (abled) :
Submit button after (disabled) :

changed the styling(color) of submit button

---

main.css

Reverts Real-Dev-Squad/website-dashboard#63

Revert "changed the styling(color) of submit button"

---

main.css

submit button earlier :
submit button later ( while disabled) : 
submit button later ( while enabled) :

styling changes of submit button

---

script.js

changing API

---

main.css

Fixed task creation form corners not round

---

index.html
main.css
package-lock.json

added create task button

---

index.html
main.css

Fixes #77 
added responsiveness to the footer.

moved footer to the bottom of the screen

---

main.css

purpose box don't go outside the form horizontally

---

main.css

Hi Aman,
Check the preview once #99 ,
On Hover button
Nomal button

Fix the issue #99

---

main.css

sync develop to main

---

main.css
script.js
task/create.html

Dashboard form enhancement for #106 
https://user-images.githubusercontent.com/20744671/141986740-b671b4ff-3d41-4187-aa87-2d99390573ac.mp4

Dashboard form enhancement

---

main.css
script.js
task/create.html

**Bugs fixed** :point_down: 
closes : #102

fixed bugs for dashboard site

---

main.css
script.js
task/create.html

Enhanced ends-on section

---

README.md
package-lock.json
package.json
src/helpers/loadENV.js
src/style.css
src/task/index.html
src/task/script.js

staging-API beging used for dev

---

src/task/index.html
src/task/script.js
src/task/style.css

updated task status and made necessary changes

---

src/task/index.html
src/task/script.js
src/task/style.css

content will be hidden untill script loads(task page)

---

src/task/script.js

- Fixed auto-clear up of filled information if task creation fails
https://user-images.githubusercontent.com/26904087/152802423-e9c9db05-a750-45b5-b6e4-947ea43f4d98.mp4

Fixed auto clear up of filled information if task creation fails

---

src/task/index.html
src/task/script.js
test.js

1. Show spinner till the request is in progress when submit is clicked. #1
https://github.com/iAmAshuSahoo/website-dashboard/issues/1
2. Task gets submitted when Assignee name is empty 
https://github.com/iAmAshuSahoo/website-dashboard/issues/2
3. Prevent submitting form on keypress of Enter
https://github.com/iAmAshuSahoo/website-dashboard/issues/3
4. Write puppeteer test cases
https://github.com/iAmAshuSahoo/website-dashboard/issues/4

Submit enabled when Assignee name is not proper

---

package-lock.json
src/task/style.css

Closes: Issue No. #177 
Here's the demo:
[rds.webm](https://user-images.githubusercontent.com/35677839/179937999-65ac62ef-927d-4067-b1db-b41d8a3d42d1.webm)

fix: added scrollbar to the autocomplete-search

---

src/profile/constants.js
src/profile/script.js
src/profile/utils.js

* Fix the data going in body of the approve button call
* Fix the data going in body of the approve button call
* updated minor changes
* updated yoe data going
* improvements in code structure
* improvements in code structure
* improvements in code structure
* removed irrelevant comments and moved createElement in a reusable method
Co-authored-by: Ankush Dharkar <ankushdharkar@users.noreply.github.com>

Fix the data going in body of the approve button call

---

src/task/script.js

Fix hide/show functionality for feature/group radio button

---

src/task/script.js

Closes #239 
- Removed the object nesting in the task data sent to backend

Removed the `taskLevel` object nesting

---

src/online-members/online-members.css
src/online-members/script.js
src/online-members/utils.js

On clicking members to get task data, an API call with null as the user name was being made, That is being fixed in this

Fix: tasks/null api call when clicked on users

---

src/task/index.html
src/task/script.js
src/task/style.css

NOTE: Don't merge this PR for now, there are other PRs in the backend which are need to be merged
- when the superuser is creating tasks they get an assignee field, where they can provide the assignee of the task, 
- This feature will allow them to get suggested users based on the skills that they have selected in the category field

added a feature to get suggested users based on skills

---

src/admin-panel/index.js

changed create level request body due to the new changes in backend

fixed req body

---

src/admin-panel/index.js

fix for level issue

---

src/user-management/constants.js
src/user-management/index.html
src/user-management/script.js
src/user-management/style.css

Closes #248
- fixes user card placement
- showing only those user's on the listing screen whose archived role is false
- added pagination on the user listing screen: at a time only 100 users will be fetched if we want to see more users, we need to hit next button, on each click on next button, next 100 users will be fetched, and shown on the listing screen, to see the previous list of user we need to click the previous button, on the first page previous button is disabled and on the last page next button is disabled
- added search functionality of particular user by username
- yes
https://user-images.githubusercontent.com/54801934/205439399-5ef0e490-71b7-48e4-a99d-1beb4d3bd69e.mp4

adds pagination and search functionality on user list

---

admin-panel/index.html
featureFlag/index.html
index.html
online-members/online-members.html
profile/index.html
task/index.html
taskEvents/index.html
users/details/index.html
users/index.html
wallet/index.html

- The MIME type of the files is being changed with adding the absolute path of the files.

Added absolute path for every js, css and assets file

---

goal/index.html
goal/script.js
goal/style.css
index.html
script.js

1. `index.html` : Hide the `Create Goal` button when the feature flag is not enabled.
2. `script.js` : Add the feature flag to the `Create Goal` button.
3. `goal/index.html` : Hide the Create goal form when the feature flag is not enabled. and show the 404 error message.
4. `goal/script.js` : Add the feature flag to the `Create Goal` form.
5. `goal/style.css` : Add the style for the 404 error message.
- Add `?dev=true` to the URL to access the `Create Goal` button in the `index.html` page.
- Add `?dev=true` to the URL to access the `Create Goal` form in the `goal/index.html` page.

button and page added behind the feature flag

---

package.json
yarn.lock

Move puppeteer to dev-dependencies

---

users/script.js
users/style.css

filter api fix and footer alignment

---

__tests__/discord-groups/discord-group.test.js
discord-groups/constants.js
discord-groups/index.html
discord-groups/script.js
discord-groups/style.css
discord-groups/utils.js
index.html
mock-data/discord-groups/index.js
mock-data/users/index.js

Discord groups

---

discord-groups/script.js
package.json

Add check for user being achieved
if they are archived we show them an error message indicating they can't use this feature.
It is a part of the following issue: https://github.com/Real-Dev-Squad/website-backend/issues/1108

show error message for archived users

---

package.json
yarn.lock

Bug: tests failing on local 
update puppeteer package 
reference we looked to find solution : https://archive.jestjs.io/docs/uk/23.x/puppeteer

bug: update package puppeteer

---

extension-requests/script.js
extension-requests/style.css

Changed the CSS to fix the cards displayed extension requests page.
before: 
after: 
https://github.com/Real-Dev-Squad/website-dashboard/assets/98796547/347df4b8-eb85-460f-a459-e161bce60828

Fix CSS of extension-requests page

---

discord-groups/index.html
discord-groups/style.css
extension-requests/script.js
extension-requests/style.css
package.json
profile/utils.js
yarn.lock

Date: 20/06/2023
Developer Name: @chaithraramesh31 
PR Number(s):- 
Issue Ticket Number:- #370
Backend changes
Frontend Changes
[x] Yes
[ ] No
Database changes
[ ] Yes
[x] No
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
[ ] Yes
[x] No
Deployment notes(Any special instructions for the deployment)
[ ] Yes
[x] No
Tested in staging
[x] Yes
[ ] No
List of PRs going in this Sync: #373
Videos
I have attached the videos of both desktop and mobile views of the discord-group page.
https://github.com/Real-Dev-Squad/website-dashboard/assets/111289485/9ee8e662-be2c-4b2e-a786-659cf5f13fdc
https://github.com/Real-Dev-Squad/website-dashboard/assets/111289485/ace252c8-cab9-4377-9da4-f391eb94d527

Sync dev to main

---

standup/script.js

FIX : Issue of standup display feature

---

task/script.js

Parent Ticket https://github.com/Real-Dev-Squad/website-backend/issues/1184
This change adds the feature flag `userStatusFlag` to the `/tasks` POST API. This feature flag allows us to change user status on new task creation

Add feature flag userStatusFlag

---

groups/style.css
yarn.lock

**Developer Name:** @mohibkay 
**PR Number(s):-** 
- #418 
**Issue Ticket Number:-** 
- #411  
I have attached the videos for reference
https://github.com/Real-Dev-Squad/website-dashboard/assets/66241121/70dfc6bb-d804-4410-ac86-1a9bb0e5bedb

Dev to main sync

---

users/script.js

Fix the error when testing the user/details page not found

Update href url

---

__tests__/user-details/Intro-button.test.js
mock-data/user-details/index.js

**Ticket**
- #441
**Test Description**
- Should show a tooltip on button hover for non-superusers
- Check if the element has a disabled selector

Pivot button test

---

__tests__/extension-requests/extension-requests.test.js

Adds missing mock data 

---

extension-requests/local-utils.js
extension-requests/style.css

Issue: https://github.com/Real-Dev-Squad/website-dashboard/issues/483
Description: 
- Fixes issue where extension cards triggering update failed animation even though the update was successful
- Minor css changes
https://github.com/Real-Dev-Squad/website-dashboard/assets/98796547/ddc52018-c336-4d2d-82a1-b81bdaef0899

Fixes extension card update issue

---

__tests__/users/onboarding31days.test.js
users/script.js

closes #495 #469 
**Is Development Tested?**
Yes
**Frontend Changes**
yes
**Test coverage stats:**
**Before**
**After**
[Screencast from 12-09-23 01:44:02 AM IST.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/55826451/2e96b0e2-1691-4348-b488-b51393f34f81)

ONBOARDING Users status for more than 31 days 

---

constants.js
users/discord/index.html

Issue: #532
**Description**-Fix Profile Picture Display for Users without Profile Pictures 
What is the change?
Added dummy Picture for users without Profile Pictures
Is Development Tested?
Before / After Change Screenshots
Before :
After :
Test Coverage-
Video--
https://github.com/Real-Dev-Squad/website-dashboard/assets/91171097/077bff33-e566-4bd9-907f-2b0b6060e6d3

Fix Profile Picture Display for Users without Profile Pictures #532

---

__tests__/user-details/task-duedate-hover.test.js
__tests__/users/onboarding-31-days-multiple-selections.test.js
__tests__/users/onboarding31days.test.js
users/details/script.js
users/script.js

Hello,
I have removed the feature flag for the features because they were working fine.

Remove Feature flag for task due date hover and onboarding > 31 days

---

style.css

Fixes #564 
This pull request addresses an alignment issue within the user profile and image display. Previously, the user's profile and image were not correctly aligned, with the options displayed on the left.

navbar alignment fix for user profile

---

script.js
style.css

Fixes #568 
This pull request addresses an alignment issue within the sign-in button Previously,The sign-in button  was not correctly aligned on the home page.
https://github.com/Real-Dev-Squad/website-dashboard/assets/84411728/bcd4a88f-55ff-41e7-a910-906ef850fa7f

Fix sign in button alignment on home page

---

__tests__/home/home.test.js
script.js
style.css

Enhance Mobile Navbar Behavior and Styling #531
The hamburger menu should close when the user clicks anywhere on the screen, outside of the navigation menu. And the hamburger menu and the page background should have a clear visual distinction for better usability.
https://github.com/Real-Dev-Squad/website-dashboard/assets/140648846/73857b6b-1500-4c37-9a69-6e200d5a2f83
**Before**
**After**

fix/mobile-navbar: fixed issues in hamburger menu

---

style.css

Enhance Mobile Navbar and Styling #531
The CSS of hamburger menu did not match with another dropdown menu on dashboard site.
**Before**
**After**

fix/mobile-hamburger: fixed the styling of hamburger menu

---

__tests__/groups/group.test.js
groups/script.js
groups/utils.js

- https://github.com/Real-Dev-Squad/website-dashboard/issues/592
Description: 
- Removes the feature flag for the discord group page.
- Removes the obsolete code.
Note: This needs to be merged with the backend PR : https://github.com/Real-Dev-Squad/website-backend/pull/1637
Before feature flag removal:
[before.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/48379860/2e6baf09-0f2e-4396-bb1f-f8c45ff19791)
After feature flag removal:
[After.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/48379860/1e8ab50a-22fa-44e0-aa41-fa5c39075b91)

feature flag removal

---

__tests__/extension-requests/extension-requests.test.js
__tests__/taskRequests/taskRequestDetails.test.js
mock-data/taskRequests/index.js
taskRequests/details/index.html
taskRequests/details/script.js
taskRequests/details/style.css
utils/time/index.js

Issue Ticket Number:-
- [#1606](https://github.com/Real-Dev-Squad/website-dashboard/issues/546)
Backend changes
Frontend Changes
Database changes
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
None
- Adds a modal which shows the proposed deadline and description.
- Fixes the oversize image of the requestor
- Adds reject button (but since API not yet ready hence commented the code)
[screen-capture (4).webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/97341921/89b8c144-bce0-4df6-9f73-96636265c523)

Fix Task Request Details Page

---

__tests__/extension-requests/extension-requests.test.js
extension-requests/script.js
extension-requests/style.css

Design Doc: https://docs.google.com/document/d/14Go2dQVH9B9c-k-VUzM4pg4CZesYJmlHugBFSbRDp0c/edit?usp=sharing
UI Fixes related to extention request card, please refer design doc for more details.
NA
Scenario: On hovering timer icon
Complete Video of Subtask1,2,3
https://github.com/Real-Dev-Squad/website-dashboard/assets/22474104/209501df-3431-478e-ad34-697bdbcd68ed

UI/UX Improvements - Accordian and extention request card

---

__tests__/user-details/task-duedate-hover.test.js
users/details/constants.js
users/details/utils.js

Some of the statuses are showing in snake cases based on word count.
- Convert all the statutes into readable format
- https://github.com/Real-Dev-Squad/website-dashboard/issues/601
NA
Run `yarn test` and there you can see the test case running.

Chore : Minor improvements

---

__tests__/taskRequests/taskRequest.test.js
mock-data/taskRequests/index.js
taskRequests/constants.js
taskRequests/index.html
taskRequests/script.js
taskRequests/style.css
taskRequests/util.js
utils.js

Date: 20 November 2023
Developer Name: @Ajeyakrishna-k 
----
- #544 
- Updates the current filter modal and sort modal
- Adds intersection observer for pagination
- Passes the filters and sort selected as query params in GET /taskRequests api.
Is Under Feature Flag 
Database changes
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
Is Development Tested?
https://github.com/Real-Dev-Squad/website-dashboard/assets/98796547/031649ca-6673-43be-a7cc-38efb82db800
https://github.com/Real-Dev-Squad/website-dashboard/assets/98796547/f048218e-e98e-4515-9dc1-977bb6840dde
https://github.com/Real-Dev-Squad/website-dashboard/assets/98796547/0526b5a6-c4af-44ae-9178-8f4b4dac7462

Adds pagination, filters and sorting on task requests listing page

---

index.html

Date:02/12/2023
----
fix the broken URLs in dashboard site
**Documentation Updated?**
-   [ ] Yes
-   [x] No
_If your feature adds a new API, then documentation related to the feature like API-Contracts, and Data-models  must be updated._
**Breaking Changes**
-   [ ] Yes
-   [x] No
_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._
**Development Tested?**
-   [x] Yes
-   [ ] No
_Confirm whether the changes have been tested locally during development._
**Tested in Staging?**
-   [ ] Yes
-   [x] No
_Indicate whether the changes have been tested in the staging environment._
**Under Feature Flag**
-   [ ] Yes
-   [x] No
_Specify if the changes are currently under a feature flag._
**Database Changes**
-   [ ] Yes
-   [x] No …

fix for navbar urls

---

__tests__/groups/group.test.js
groups/script.js

- Resolved the issue where the Discord group sharable link was not functional.
- Users can now successfully access and join the Discord group using the provided link.
https://github.com/Real-Dev-Squad/website-dashboard/assets/70854507/897d197d-a8af-42d6-9662-d0c9cd9c7f50

FIX: Share group using URL

---

__tests__/user-details/task-duedate-hover.test.js
users/details/script.js

Remove feature flag from new task accordion UI
- https://github.com/Real-Dev-Squad/website-dashboard/issues/601
NA
https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/c1fa0dcb-946c-487d-bc32-e235601bd95a

Feat : Removed feature flag from  task accordion

---

__tests__/taskRequests/taskRequest.test.js
taskRequests/style.css

Date: 4 December 2023
Developer Name: @Ajeyakrishna-k 
----
Fixes css of task requests listing page filter and sort modal
**Breaking Changes**
-   [ ] Yes
-   [x] No
_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._
**Development Tested?**
-   [x] Yes
-   [ ] No
_Confirm whether the changes have been tested locally during development._
**Tested in Staging?**
-   [x] Yes
-   [ ] No
_Indicate whether the changes have been tested in the staging environment._
**Under Feature Flag**
-   [x] Yes
-   [ ] No
**Database Changes**
-   [ ] Yes
-   [x] No
before:
after:

Fixes css of task requests listing page filter and sort modal

---

__tests__/task-requests/task-request.test.js
task-requests/script.js

Date: 22 December 2023
Developer Name: @Ajeyakrishna-k 
----
Removes dev flag from fetch task requests api calls
**Documentation Updated?**
-   [ ] Yes
-   [x] No
**Breaking Changes**
-   [ ] Yes
-   [x] No
**Development Tested?**
-   [x] Yes
-   [ ] No
**Tested in Staging?**
-   [x] Yes
-   [ ] No
**Under Feature Flag**
-   [x] Yes
-   [ ] No
**Database Changes**
-   [ ] Yes
-   [x] No

Removes dev flag from fetch task requests api

---

__tests__/task-requests/task-request.test.js
__tests__/tasks/profile-picture.test.js
__tests__/users/App.test.js
applications/utils.js
constants.js
extension-requests/index.html
groups/index.html
helpers/loadENV.js
index.html
online-members/online-members.html
profile/index.html
standup/index.html
task-requests/details/script.js
users/details/index.html
users/discord/index.html
users/index.html

Date: 27-02-2024
Developer Name: Pavan Bhat
---
#v0Kn1KsLZbWWs0V9A6Pj
**This modification ensures that the root page of the website dashboard can now communicate with staging-APIs (staging-api.realdevsquad.com).**
Previously, the root page did not recognize the environment variable API_BASE_URL due to the absence of the loadEnv script. Consequently, the value of API_BASE_URL was being sourced from constants, where it was hard coded to the production API
<details>
</details>
<details>
</details>

Enabling Staging-API Access on Website Dashboard 

---

extension-requests/script.js

Date: 31 Jan 2023
Developer Name: Joy Gupta
---
- https://github.com/Real-Dev-Squad/website-dashboard/issues/688
In the screen recording it can be seen that the dev flag is missing although I have checked it is under the feature flag. The reason is extension logs will be removed from the feature flag and I've raised a separate PR for the same so it won't create an issue.
Fixed the height for the accordion.
<details>
<summary> The Accordion height issue is also fixed.</summary>
https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/2c0ac930-6ebf-4eb2-a3b7-51d5c7398d46
</details>
NA
NA

Bug : Fixed accordion height issue

---

script.js

Date: 1 Feb 2024
Developer Name: Joy Gupta
---
- https://github.com/Real-Dev-Squad/website-dashboard/issues/691
Handled error in the profile section part of the navbar. Now user info is visible.
Cannot add a test case as the `home.test.js` file has already intercepted the `/self` API which has test cases implemented for positive use cases. So I cannot modify the intercepted API response.

Bug : Fixed profile section missing issue

---

__tests__/users/applyFilterPagination.test.js
mock-data/users/mockdata.js
users/script.js

Date: 07 February 2024
Developer Name: @Achintya-Chatterjee 
---
https://github.com/Real-Dev-Squad/website-dashboard/issues/678
Pagination is missing when multiple filter is applied and user count is 100+
<details>
[Screencast from 09-02-24 02:15:52 AM IST.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/55826451/d463a651-a943-43da-8641-229c34ea7e83)
</details>
<details>
</details>

Add Pagination on the Apply Filter Button

---

__tests__/task-requests/task-request.test.js
task-requests/constants.js
task-requests/script.js
task-requests/util.js

Date: 19-02-2024
---
closes #697 
- Adds query params to url to save the page state
- Loads the page with respect to filters and sort specified in url query params
https://github.com/Real-Dev-Squad/website-dashboard/assets/88454618/fb0348ec-a937-4f1b-b403-6f4566c13096
- The default sort by is Oldest First and filter status is Pending.

Add query params to task requests page url

---

__tests__/task-requests/task-request.test.js
task-requests/constants.js
task-requests/script.js
task-requests/util.js

Date: 21-02-2024
---
#702 
#697 
- Adds query params to url to save the page state
- Loads the page with respect to filters and sort specified in url query params
https://github.com/Real-Dev-Squad/website-dashboard/assets/88454618/dde2aa58-69fb-4f49-b3ad-33395ee43afc
- The default sort by is Oldest First and filter status is Pending.

Add query params to task requests page url (#702)

---

package.json
yarn.lock

Added local SSL proxy command and package.
<details>
</details>
<details>
</details>

config: added local ssl proxy

---

constants.js
groups/utils.js

Date: 05-03-2034
Developer Name: Pavan Bhat
---
Doing it as part of #676 
In the staging environment, we are hitting prod API for the discord groups page [https://dashboard.realdevsquad.com/groups]  of the dashboard site
<details>
</details>
<details>
</details>

Started honoring window.API_BASE_URL for the groups page

---

__tests__/task-requests/task-request.test.js

Date: 09-03-2024
---
This PR adds tests for changes made in #712 
-  #712 
<details>
</details>
<details>
</details>

Add Tests for UI Feedback Improvements on Task-Requests Page

---

requests/constants.js
requests/index.html
requests/script.js
requests/style.css
requests/util.js

Closes - #709 
Added intersection Observer for infinite loading
<details>
https://github.com/Real-Dev-Squad/website-dashboard/assets/70854507/b2ac35aa-b90e-450f-98e4-9fc4fd7bdd8a
</details>
<details>
@Swapnil099 is writing the test for the requests page 
</details>

FEATURE : Added Intersection observer for infinite scrolling

---

__tests__/task-requests/task-requestDetails.test.js
mock-data/taskRequests/index.js
task-requests/details/index.html
task-requests/details/script.js
task-requests/details/style.css

Date: 22nd March 2024
Developer Name: Tushar Goel
---
Add markdown in TCR description
<details>
</details>
<details>
</details>

Add markdown in tcr description

---

task-requests/details/style.css

Date: 26th March 2024
Developer Name: Tushar Goel
---
Enhance UI to support longer texts in markdown
<details>
</details>
<details>
</details>

Enhance modal UI to support longer texts in markdown

---

__tests__/requests/requests.test.js
mock-data/requests/index.js
requests/script.js
requests/style.css
requests/util.js

Date: 27-03-2024
---
closes #724 
This PR addresses the issue of the entire request page showing a loading state when a super user approves or rejects a request. Instead of hiding the content of the whole page, a loading spinner is now displayed in the specific request card until the action is completed. The particular card is re-rendered instead of the whole page. 
The requests page did not have tests. So did the setup and added the test related to current change.
https://github.com/Real-Dev-Squad/website-dashboard/assets/88454618/8533e08a-d1a6-4d9e-ab1b-b0270f78d369
https://github.com/Real-Dev-Squad/website-dashboard/assets/88454618/b438dd08-7304-4780-bf0e-2faea6926158
<details>
</details>
The requests page did not have …

Fix Content Hiding And Add Loading Spinner in Specific Request Card on Approval/Rejection Action In Request Management Page

---

task-requests/details/style.css

Date: 8th April
Developer Name: Tushar Goel 
---
Fix Modal CSS
<details>
</details>
<details>
</details>

Fix Modal CSS for images and table in markdown

---

task-requests/details/style.css

* Fix Modal CSS
* Address review comment
* Address review comments
---------
Date: 9th April 2024
Developer Name: Tushar Goel
---
Fix Modal CSS for images and table in markdown
<details>
</details>
<details>
</details>

Fix Modal CSS for images and table in markdown (#739)

---

task-requests/details/style.css

Date: 9th April 2024
Developer Name: Tushar Goel
---
Fix Modal CSS
<details>
</details>
<details>
</details>

Fix modal CSS

---

task-requests/details/style.css

Date: 
Developer Name: 
---
<details>
</details>
<details>
</details>

sync : dev to main

---

__tests__/home/home.test.js
index.html
script.js

- #749 
Added request button to the home page with feature flag implementation.
<details>
With FF
</details>
<details>
</details>

added request anchor button to home page with FF

---

groups/render.js
groups/script.js

Profile loading showing with login button
Add me and Remove Me not working in production
Handle render function deleting non existing element case
Date: 30/05/2024
Developer Name: @pallabez 
---
#763
Add me and remove me not working in production
ProfileLoader showing along with login button
<details>
</details>
<details>
</details>

Discord groups bug fixes

---

identity-service-logs/index.html
identity-service-logs/script.js
identity-service-logs/style.css
identity-service-logs/utils.js

Date: 07-08-2024
Developer Name: @lakshayman 
---
https://github.com/Real-Dev-Squad/website-dashboard/issues/758
I added a fix for users who are not logged in. The page is not giving any errors for users who are not logged in.
<details>
<summary>Image showing alert when user is not logged-in</summary>
</details>

Added a fix for not loggedin users

---

__tests__/applications/applications.test.js
applications/script.js
applications/style.css
applications/utils.js

- closes #783 
In this PR super user can view the particular application by passing in the id of application in query params
<details>
https://github.com/user-attachments/assets/46cafae6-a174-46d3-805d-9ea9c164fd70
<details>
</details>

Fix applications route to render application by id

---

__tests__/applications/applications.test.js
applications/script.js
applications/style.css

Date: 26 Aug 2024
Developer Name: Samarpan Harit
---
- Closes #792 
1. Add id in query params when view details btn is clicked
2. When applications/?id= page is opened, applications should load applications behind the modal 
3. Check the selected filter value when page with status filter applied is reloaded
4. Remove status query param from the url when status filter is cleared
5. Truncate multi-line text in application cards
6. Hidden DOM elements should not be rendered on applications page as they occupy space causing weird gaps
7. Add necessary spacing on the applications page
<details>
https://github.com/user-attachments/assets/cffff010-59a4-489b-8623-d0276ca707db
</details>
<details>
<summary>Screenshot 2</summary> …

Fix /applications page bugs

---

identity-service-logs/script.js
identity-service-logs/utils.js

Date: 29/08/2024
Developer Name: @lakshayman 
Fixed a constant (SUPER_USER) import that is causing a bug.

Fixing SUPER_USER import that created bug

---

applications/script.js

Date: 28 Aug 2024
Developer Name: Samarpan Harit
---
closes #797 
1. Before adding a query param in the URL, check if it already exists in the URL
2. If yes, then remove it
3. Add the query param to the URL
<details>
https://github.com/user-attachments/assets/f55d2537-6116-43d2-9562-6432fdad3849
</details>
<details>
</details>

Fix status filter query param on applications page

---

applications/index.html
applications/script.js
applications/style.css

Date: 30 Aug 2024
Developer Name: Samarpan Harit
---
Closes #804 
1. Make the reject button smaller
2.  Change the application action buttons behaviour
- If application is in pending state
- Both accept/reject buttons should be active
- If application is in accepted or rejected state
- Both the accept/reject buttons should be hidden
- A message should be shown = Application is already accepted / Application is already rejected
<details>
https://github.com/user-attachments/assets/2545ad77-65f4-45ea-8230-0bded2578da9
</details>
<details>
</details>

Make reject button smaller and fix modal action buttons state on /applications page

---

standup/script.js
standup/utils.js

Date: 30/08/2024
Developer Name: sameer supe 
---
- Closes #794
fixes user details in table on standup page.
updated standup/utils.js createElement which was in conflict with similar fn in global/utils.js added in #768, createStandupElement
<details>
https://github.com/user-attachments/assets/a9fc7a8b-7775-48fd-b377-3fb41c7a3f53
</details>
<details>
</details>

fix standup page

---

task-requests/script.js

Date: `03 Sep 2024`
Developer Name: Vaibhav Singh
---
- Closes #810 
Fixed the wrong error message being displayed for unauthenticated users at the [dashboard site/task-requests](https://dashboard.realdevsquad.com/task-requests) page from "Unexpected error occurred" to correct respective authentication error.
<details>
</details>
Test Coverage only for task-requests: All tests passed
<details>
</details>

fix: Wong error message for Unauthenticated user

---

task-requests/style.css

Date: 03 Sep 2024
Developer Name: Vaibhav Singh
---
Fixed error description styles breaking on mobile devices.
<details>
Mobile:
Desktop:
</details>
<details>
</details>

fix: Error style breaking on mobile devices

---

task-requests/style.css

Reverts Real-Dev-Squad/website-dashboard#813

Revert "fix: Error style breaking on mobile devices"

---

__tests__/groups/group.test.js
groups/createElements.js
groups/render.js
groups/script.js
groups/style.css
groups/utils.js

Date: 19-09-2024
Developer Name: Surendar Singh
---
- #800 
- Added a "No group found" container when there are no groups present on search input in the group page
- Changed the search filter for groups to prefix of the word(s)
<details>
<summary>Screenshot</summary>
</details>
<details>
<summary>Working Video</summary>
https://github.com/user-attachments/assets/12c50cc8-3181-49b6-804c-05505c7eb0ad
</details>
<details>
Groups test are passed
</details>

feat: add no group found and search with prefix name

---

__tests__/home/home.test.js
index.html
style.css

Reverts Real-Dev-Squad/website-dashboard#817

Revert "Improve Dashboard Site Homepage"

---

identity-service-logs/index.html
identity-service-logs/script.js
identity-service-logs/utils.js

Date: 20 Sep 2024
Developer Name: Utkarsh Bansal
---
- Closes #827 
Removed the previously next and prev button and added Intersection Observer so that when you reach the bottom of the page the new data is automatically fetched from api and added.
<details>
Before the changes
https://github.com/user-attachments/assets/a8de92e7-bd0b-41b9-9b1f-7fd52516dd78
</details>
<details>
<summary>Screenshot 2</summary>
After Changes
https://github.com/user-attachments/assets/515c22c8-8708-4de6-8f46-3ca0ff89f01b
</details>
<details>
</details>

Enhancement: Make the /identity-service-logs UI infinite scroll

---

__tests__/applications/applications.test.js
applications/index.html
applications/script.js
applications/style.css

Date: 23-09-2024
Developer Name: Harshavardhan
---
https://github.com/Real-Dev-Squad/website-dashboard/issues/828
- Change the filter ui to
- Show applied filter 
- option to remove the applied filter
<details>
https://github.com/user-attachments/assets/5f81342e-5ffe-4f19-a855-0a45f5388140
</details>
<details>
</details>

Show applied filter on applications page with delete option

---

__tests__/users/user-management-home-screen.test.js
users/constants.js
users/index.html
users/script.js
users/style.css

Reverts Real-Dev-Squad/website-dashboard#854

Revert "Feature/infinite user loading"

---

package.json
task-requests/details/script.js

Date: 09 Oct 2024
Developer Name: Nawal Rai
---
- closes #880 
- Made disabled forced 4 spaces for sub lists true
<details>
- Before
- After
</details>
<details>
</details>

Fixed indexing of rendering list

---

online-members/online-members.css
online-members/script.js

Date: 08/10/2024
Developer Name: Sameer Supe
---
- Closes #876 
changed a value in script.js which was preventing task section from rendering, also changes a stylesheet value
<details>
https://github.com/user-attachments/assets/07009fc3-9158-439f-ae98-7b74f3a5a055
</details>
<details>
</details>

fix online-members page task section

---

__tests__/groups/group.test.js
groups/script.js
groups/utils.js

Date: 09 oct 2024
Developer Name: Suvidh Kaushik
---
- Closes #874 
Removal of the dev feature flag from the groups page and updating of tests according to the change 
<details>
<summary>Before Removal</summary>
</details>
<details>
<summary>After Removal</summary>
</details>
<details>
</details>
Backend PR where feature flag was removed - [#1637 website-backend](https://github.com/Real-Dev-Squad/website-backend/pull/1637)

chore: remove feature flag from groups 

---

__tests__/task-requests/task-requestDetails.test.js

Date: 2 Nov 2024
Developer Name: Anuj Chhikara
---
- Closes #904 
This pull request addresses the inconsistent behavior of the task-requestDetails.test.js test, which has been failing intermittently in the GitHub Actions environment while passing reliably in local setups. The goal of this fix is to ensure that the test passes consistently across all environments, enhancing test reliability and confidence in our CI pipeline.
<details>
</details>
<details>
</details>

task-requestDetails test fix

---

feed/script.js
feed/style.css
feed/utils.js

Date: 15-02-2025
Developer Name: @vinit717 
---
- closes #945 
Fix the search filter by implementing the debouncing and also a error text message has been added
<details>
</details>
- https://github.com/Real-Dev-Squad/website-dashboard/issues/939

Fix activity feed

---

style.css

Date: 22/02/2025
Developer Name: Vignesh B S
---
- Closes #949 
- Removed fixed height (80vh) from buttonSection that was causing spacing issues
- Set height to auto for mobile view
- Added appropriate top margin for better spacing
- Maintained single column layout for better mobile UX
<details>
</details>
<details>
</details>
The user must be logged in with ***super user access*** to see all the options.

Fix: Fixed dashboard mobile view.

---

__tests__/requests/requests.test.js
global.css
mock-data/requests/index.js
requests/constants.js
requests/index.html
requests/script.js
requests/style.css
requests/util.js
style.css

Date: 27 Feb, 2025
Developer Name: @VinuB-Dev  @AnujChhikara 
---
- Closes #949
- Closes #864 
- #950  
- #942 
- #952 
- #954 
<details>
</details>
<details>
</details>

Dev to Main Sync 

---

__tests__/requests/requests.test.js
requests/index.html
requests/script.js

Date: 22 March, 2025
Developer Name: @pankajjs 
---
- Closes #960 
This PR fixes the mismatch in request page url and selected request tab.
-It correctly selects the request tab link given the request page url.
-It matches the request tab link with given page url even after reloading.
<details>
<summary>Working Video</summary>
https://github.com/user-attachments/assets/5a1e2267-7a1b-4289-a092-68eeeebe13a6
</details>
<details>
<summary>Screenshots</summary>
</details>

Select the correct request tab link for request page url

---

__tests__/feed/feed.test.js
feed/index.html
feed/script.js
feed/style.css
feed/utils.js
mock-data/logs/index.js

Date: 29-03-2025
Developer Name: vinit
---
- closes #956
Implement a date ranger picker where the user can select a date range using single calendar

Implement date range picker

---

__tests__/requests/requests.test.js
requests/index.html
requests/script.js

Date: 7 April, 2025
Developer Name: @pankajjs 
---
- Closes #972 
This PR fixes an issue where error UI toast were being shown in /requests page after refreshing the page. Now, it correctly shows the requests card and hides the error UI toast after refreshing the page.
<details>
<summary>Working Video</summary>
https://github.com/user-attachments/assets/a776fc4f-e9a2-4d69-a412-f1093290081c
</details>
<details>
<summary>Screenshots</summary>
</details>

display requests cards after reloading the /requests page

---

README.md

Date: 18/04/2025
Developer Name: JC CODER
---
This pr updates the readme to be more detailed and guide users on how to setup the project and run locally.
<details>
</details>
<details>
</details>

docs: update README.md for clarity and additional setup instructions

---

__tests__/applications/applications.test.js
__tests__/components/toast.test.js
__tests__/extension-requests/extension-requests.test.js
__tests__/groups/group.test.js
__tests__/identity-service-logs/identity-service-logs.test.js
__tests__/profile-diff-details/profile-diff-details.test.js
__tests__/requests/requests.test.js
__tests__/task-requests/task-requestDetails.test.js
applications/index.html
applications/script.js
applications/utils.js
components/toast/script.js
components/toast/style.css
extension-requests/index.html
extension-requests/script.js
groups/index.html
groups/script.js
identity-service-logs/index.html
identity-service-logs/script.js
identity-service-logs/utils.js
images/x-icon-green.svg
images/x-icon-red.svg
profile-diff-details/index.html
profile-diff-details/script.js
requests/index.html
requests/script.js
task-requests/details/index.html
task-requests/details/script.js

Date: 16 April 2025
---
- #979 
This PR includes the following changes:
- Introduced a reusable toast component
- Integrated the toast component across multiple pages for consistent feedback messaging
- Test PR of these changes is already merged into the develop branch
- #980 
<details>
- Application Page
https://github.com/user-attachments/assets/ba48c62b-8ca6-4add-b08f-2d340d68e68b
- extension-request
https://github.com/user-attachments/assets/7cd29224-f229-4e18-8aec-2056dfca831a
- groups
https://github.com/user-attachments/assets/dccb299b-3b6d-48d9-a448-cfbc3dae96e2
- identity-service-logs
https://github.com/user-attachments/assets/79a8462d-c3d0-412c-b5cc-a2ad60f98f58
- requests …

feature create resusable component for toast

---

__tests__/extension-requests/extension-requests.test.js
__tests__/requests/requests.test.js
mock-data/requests/index.js

Date: 09 May 2025
---
- #975 
- This PR adds tests for the Request Card component.
- It covers rendering of the UI and verifies the functionality for approving and rejecting requests.
🔧 Note: Tests are currently skipped as the related feature code has not yet been pushed.
<details>
</details>
<details>
</details>

test: add test for request card component

---

components/request-card/script.js

Date: 11 May 2025
---
- Closes #975 
- This PR introduces the initial part of the `createRequestCardComponent` refactoring, focusing on the creation of core UI elements.
Note for reviewer: No design changes are being made to the extension card, so most of the implementation is reused from the existing code.
- Test PR has been merged already #994 
<details>
- Note:  these are final Changes after all the PRs of this request card merged 
- Extension Request
https://github.com/user-attachments/assets/bbb406c9-33e6-49f0-9744-ec4d837f39f6
https://github.com/user-attachments/assets/ba68afa0-a4d8-4270-9a26-f5e845b267b6
https://github.com/user-attachments/assets/b4eab7c0-0b4f-4ae3-add2-9a329cf471cc
- OOO and Onboarding Requests …

feature: add function for create request card

---

components/request-card/script.js

Date: 18 May 2025
---
- #975
- This PR adds the second part of the createRequestCardComponent function, continuing the construction of the dynamic request card UI.
- First PR of the component #999 
- Test PR has been merged #994 
<details>
- Note:  these are final Changes after all the PRs of this request card merged 
- Extension Request
https://github.com/user-attachments/assets/bbb406c9-33e6-49f0-9744-ec4d837f39f6
https://github.com/user-attachments/assets/ba68afa0-a4d8-4270-9a26-f5e845b267b6
https://github.com/user-attachments/assets/b4eab7c0-0b4f-4ae3-add2-9a329cf471cc
- OOO and Onboarding Requests
https://github.com/user-attachments/assets/ceac2abf-5223-45d9-943c-c96e7ef3249f …

Feature : add create request card component - 2

---

__tests__/extension-requests/extension-requests.test.js
__tests__/requests/requests.test.js
components/request-card/constant.js
components/request-card/script.js
components/request-card/utils.js
extension-requests/index.html
extension-requests/script.js
extension-requests/style.css
images/chevron-down-black.svg
requests/index.html
requests/script.js
requests/style.css

Date: 25 May 2025
---
- #975 
- This is the final PR of request card component in this PR we have implemented the request card component under the feature flag
- Removed the Skip from the tests of this feature
- Updated some test field names to match the new component, as these tests cover card functionality under the dev flag
- Test PR #994 
<details>
- Extension Request
https://github.com/user-attachments/assets/bbb406c9-33e6-49f0-9744-ec4d837f39f6
https://github.com/user-attachments/assets/ba68afa0-a4d8-4270-9a26-f5e845b267b6
https://github.com/user-attachments/assets/b4eab7c0-0b4f-4ae3-add2-9a329cf471cc
- OOO and Onboarding Requests
https://github.com/user-attachments/assets/ceac2abf-5223-45d9-943c-c96e7ef3249f …

feature: Implementation of the request card component

---

__tests__/extension-requests/extension-requests.test.js
__tests__/requests/requests.test.js
components/request-card/constant.js
components/request-card/script.js
components/request-card/utils.js
extension-requests/index.html
extension-requests/script.js
extension-requests/style.css
images/chevron-down-black.svg
requests/index.html
requests/script.js
requests/style.css

Date: 22 May 2025
---
- #975 
- This PR introduces a new function createActionContainer responsible for dynamically generating action elements (buttons, status indicators, input fields) for request cards based on the request type and status.
- Test PR #994 
<details>
- Note:  these are final Changes after all the PRs of this request card merged 
- Extension Request
https://github.com/user-attachments/assets/bbb406c9-33e6-49f0-9744-ec4d837f39f6
https://github.com/user-attachments/assets/ba68afa0-a4d8-4270-9a26-f5e845b267b6
https://github.com/user-attachments/assets/b4eab7c0-0b4f-4ae3-add2-9a329cf471cc
- OOO and Onboarding Requests
https://github.com/user-attachments/assets/ceac2abf-5223-45d9-943c-c96e7ef3249f …

feat: add util functions for request card
